config/routes.rb
Layouter::Application.routes.draw do

  resources :facilitators

  resources :imports

  resources :news_sectors

  resources :round_stock_constants

  resources :constants

  resources :player_clients

  resources :news_companies

  resources :client_earnings

  resources :player_earnings

  resources :client_transactions

  resources :player_transactions

  resources :client_players

  resources :clients

  resources :player_assessments

  resources :portfolio_allocations

  resources :player_promises

  resources :player_fee_structures

  resources :company_financials

  resources :investment_types

  resources :economic_parameter_values

  resources :economic_parameter_s

  resources :round_news

  resources :rounds

  resources :simulations

  resources :economic_parameters

  resources :news

  resources :scheme_prices

  resources :schemes

  resources :gold_prices

  resources :fixed_deposits

  resources :debt_paper_prices

  resources :debt_papers

  resources :stock_prices

  resources :stocks

  resources :companies

  resources :sectors

  resources :players

  resources :student_group_users

  resources :facilitator_groups

  resources :student_groups

  devise_for :users
  root :to=>'welcome#landing_page'
  resources :plugin_samples
  resources :jquery_themes
  resources :font_themes
  resources :icon_themes
  resources :temps
  resources :pages
  resources :page_layouts
  resources :layout_themes
  resources :color_themes


  #my get routes
  get '/landing_page'=>'welcome#landing_page'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match 'initiate_round'=>'simulations#initiate_round'
  match 'start_round'=>'simulations#start_round'
  match 'end_round'=>'simulations#end_round'
  match 'player_decision_page'=>'welcome#decision_page'
  match 'player_transaction_page'=>'welcome#transaction_page'
  match 'company_stock_prices'=>'stock_prices#get_stock_prices_in_json'
  match 'current_stock_price' =>'stock_prices#get_current_stock_price'






end

app/models/student_group.rb
class StudentGroup < ActiveRecord::Base
  has_many :student_group_users,:dependent => :destroy
end

app/controllers/student_groups_controller.rb
class StudentGroupsController < ApplicationController
  # GET /student_groups
  # GET /student_groups.json
  def index
    @student_groups = StudentGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_groups }
    end
  end

  # GET /student_groups/1
  # GET /student_groups/1.json
  def show
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_group }
    end
  end

  # GET /student_groups/new
  # GET /student_groups/new.json
  def new
    @facilitator_group=FacilitatorGroup.find(params[:facilitator_group_id])
    @student_group = StudentGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_group }
    end
  end

  # GET /student_groups/1/edit
  def edit
    @student_group = StudentGroup.find(params[:id])
  end

  # POST /student_groups
  # POST /student_groups.json
  def create
    @student_group = StudentGroup.new(params[:student_group])

    respond_to do |format|
      if @student_group.save
        format.html { redirect_to @student_group, notice: 'Student group was successfully created.' }
        format.json { render json: @student_group, status: :created, location: @student_group }
      else
        format.html { render action: "new" }
        format.json { render json: @student_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_groups/1
  # PUT /student_groups/1.json
  def update
    @student_group = StudentGroup.find(params[:id])

    respond_to do |format|
      if @student_group.update_attributes(params[:student_group])
        format.html { redirect_to @student_group, notice: 'Student group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_groups/1
  # DELETE /student_groups/1.json
  def destroy
    @student_group = StudentGroup.find(params[:id])
    @student_group.destroy

    respond_to do |format|
      format.html { redirect_to student_groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/student_groups_helper.rb
module StudentGroupsHelper
end

app/views/student_groups/_form.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :main_content do %>

<%= form_for(@student_group) do |f| %>
<% if @student_group.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@student_group.errors.count, "error") %> prohibited this student_group
    from being saved:</h2>

  <ul>
    <% @student_group.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


    <%= f.label :name %><br/>
    <%= f.text_field :name %>
    <br/><br/>


    <%= f.hidden_field :facilitator_group_id,:value=>@facilitator_group.id %>
    <br/><br/>

<p><%= f.submit %></p>
<% end %>
<% end %>

<%= content_for :navigation do %>
<% end %>
<%= content_for :footer do %>
<% end %>

app/views/student_groups/edit.html.erb

<%= content_for :header do %>
<h1>Editing student_group</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("show"),:size=>"100x100"), @student_group, :title=>'Show' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), student_groups_path, :title=>'Back' %>
<% end %>

app/views/student_groups/index.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :header do %>
<h1>Listing student_groups</h1>
<% end %>

<%= content_for :main_content do %>
<table>
  <tr>

    <th>Name</th>

    <th>Facilitator group</th>

    <th></th>
  </tr>

<% @student_groups.each do |student_group| %>
  <tr>

    <td><%= student_group.name %></td>

    <td><%= student_group.facilitator_group_id %></td>

    <td>
    <%= link_to image_tag(icon("show"),:size=>"64x64"), student_group, :title=>'Show' %>
    <%= link_to image_tag(icon("edit"),:size=>"64x64"), edit_student_group_path(student_group), :title=>'Edit' %>
    <%= link_to image_tag(icon("delete"),:size=>"64x64"), student_group, confirm: 'Are you sure?', method: :delete, :title=>'Delete' %>
    </td>
  </tr>
<% end %>
</table>
<% end %>

<br />
<%= content_for :navigation do %>
<% end %>
<%= content_for :extra do %>
<%= link_to image_tag('new_icon.png',:size=>"100x100"), new_student_group_path, :title=>"Add a student_group" %>
<% end %>
<%= content_for :footer do %>
<% end %>


app/views/student_groups/new.html.erb
<%= content_for :header do %>
<h1>New student_group</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), student_groups_path, :title=>'Back' %>
<% end %>


app/views/student_groups/show.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :header do %>
<% end %>

<%= content_for :main_content do %>


    <p>
      <b>Name:</b>
      <%= @student_group.name %>
    </p>


    <p>
      <b>Facilitator group:</b>
      <%= @student_group.facilitator_group_id %>
    </p>



<% end %>
<br/>
<br/>
<%= content_for :navigation do %>
<% end %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("edit"),:size=>"100x100"), edit_student_group_path(@student_group), :title=>'Edit' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), student_groups_path, :title=>'Back' %>
    <%= link_to "Manage Students",new_student_group_user_path(:student_group_id=>@student_group.id) %>
<% end %>

<%= content_for :footer do %>
<% end %>