config/routes.rb
Layouter::Application.routes.draw do

  resources :facilitators

  resources :imports

  resources :news_sectors

  resources :round_stock_constants

  resources :constants

  resources :player_clients

  resources :news_companies

  resources :client_earnings

  resources :player_earnings

  resources :client_transactions

  resources :player_transactions

  resources :client_players

  resources :clients

  resources :player_assessments

  resources :portfolio_allocations

  resources :player_promises

  resources :player_fee_structures

  resources :company_financials

  resources :investment_types

  resources :economic_parameter_values

  resources :economic_parameter_s

  resources :round_news

  resources :rounds

  resources :simulations

  resources :economic_parameters

  resources :news

  resources :scheme_prices

  resources :schemes

  resources :gold_prices

  resources :fixed_deposits

  resources :debt_paper_prices

  resources :debt_papers

  resources :stock_prices

  resources :stocks

  resources :companies

  resources :sectors

  resources :players

  resources :student_group_users

  resources :facilitator_groups

  resources :student_groups

  devise_for :users
  root :to=>'welcome#landing_page'
  resources :plugin_samples
  resources :jquery_themes
  resources :font_themes
  resources :icon_themes
  resources :temps
  resources :pages
  resources :page_layouts
  resources :layout_themes
  resources :color_themes


  #my get routes
  get '/landing_page'=>'welcome#landing_page'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match 'initiate_round'=>'simulations#initiate_round'
  match 'start_round'=>'simulations#start_round'
  match 'end_round'=>'simulations#end_round'
  match 'player_decision_page'=>'welcome#decision_page'
  match 'player_transaction_page'=>'welcome#transaction_page'
  match 'company_stock_prices'=>'stock_prices#get_stock_prices_in_json'
  match 'current_stock_price' =>'stock_prices#get_current_stock_price'






end

app/models/portfolio_allocation.rb
class PortfolioAllocation < ActiveRecord::Base
  belongs_to :player
end

app/controllers/portfolio_allocations_controller.rb
class PortfolioAllocationsController < ApplicationController
  # GET /portfolio_allocations
  # GET /portfolio_allocations.json
  def index
    @player=Player.find(params[:player_id])
    @round=Round.find(ActiveRound.first.round_id)
    @portfolio_allocations = @player.portfolio_allocations



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @portfolio_allocations }
    end
  end

  # GET /portfolio_allocations/1
  # GET /portfolio_allocations/1.json
  def show
    @portfolio_allocation = PortfolioAllocation.find(params[:id])
    @player=Player.find(@portfolio_allocation.player_id)
    @round=Round.find(ActiveRound.first.round_id)


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @portfolio_allocation }
    end
  end

  # GET /portfolio_allocations/new
  # GET /portfolio_allocations/new.json
  def new
    @player=Player.find(params[:player_id])
    @round=Round.find(ActiveRound.first.round_id)
    @portfolio_allocation = PortfolioAllocation.new

    #if @player.portfolio_allocations.count>0

       @present_portfolio_allocations=@player.portfolio_allocations.map(&:investment_type_id)

       @possible_investment_types=InvestmentType.all.collect!{|investment_type| if !@present_portfolio_allocations.include?(investment_type.id) then [investment_type.name,investment_type.id] end}.compact
     #  else
      #   @possible_investment_types=InvestmentType.all
       #end


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @portfolio_allocation }
    end
  end

  # GET /portfolio_allocations/1/edit
  def edit
    @portfolio_allocation = PortfolioAllocation.find(params[:id])
  end

  # POST /portfolio_allocations
  # POST /portfolio_allocations.json
  def create
    @portfolio_allocation = PortfolioAllocation.new(params[:portfolio_allocation])

    respond_to do |format|
      if @portfolio_allocation.save
        format.html { redirect_to @portfolio_allocation, notice: 'Portfolio allocation was successfully created.' }
        format.json { render json: @portfolio_allocation, status: :created, location: @portfolio_allocation }
      else
        format.html { render action: "new" }
        format.json { render json: @portfolio_allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /portfolio_allocations/1
  # PUT /portfolio_allocations/1.json
  def update
    @portfolio_allocation = PortfolioAllocation.find(params[:id])

    respond_to do |format|
      if @portfolio_allocation.update_attributes(params[:portfolio_allocation])
        format.html { redirect_to @portfolio_allocation, notice: 'Portfolio allocation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @portfolio_allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolio_allocations/1
  # DELETE /portfolio_allocations/1.json
  def destroy
    @portfolio_allocation = PortfolioAllocation.find(params[:id])
    @portfolio_allocation.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_allocations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/portfolio_allocations_helper.rb
module PortfolioAllocationsHelper
end

app/views/portfolio_allocations/_form.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :main_content do %>

<%= form_for(@portfolio_allocation) do |f| %>
<% if @portfolio_allocation.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@portfolio_allocation.errors.count, "error") %> prohibited this portfolio_allocation
    from being saved:</h2>

  <ul>
    <% @portfolio_allocation.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>



    <%= f.hidden_field :player_id ,:value=>@player.id%>


    <%= f.label :min_allocation %><br/>
    <%= f.number_field :min_allocation %>
    <br/><br/>

    <%= f.label :max_allocation %><br/>
    <%= f.number_field :max_allocation %>
    <br/><br/>


    <%= f.hidden_field :round_id ,:value=>@round.id%>


    <%= f.label :investment_type_id %><br/>
    <%= f.select :investment_type_id ,@possible_investment_types %>
    <br/><br/>

<p><%= f.submit %></p>
<% end %>
<% end %>

<%= content_for :navigation do %>
<% end %>
<%= content_for :footer do %>
<% end %>

app/views/portfolio_allocations/edit.html.erb

<%= content_for :header do %>
<h1>Editing portfolio_allocation</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("show"),:size=>"100x100"), @portfolio_allocation, :title=>'Show' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), portfolio_allocations_path, :title=>'Back' %>
<% end %>

app/views/portfolio_allocations/index.html.erb
<%= content_for :head do %>
    <script type="text/javascript">
        $(function() {
        });
    </script>
<% end %>

<%= content_for :header do %>
    <h1>Listing portfolio_allocations</h1>
<% end %>

<%= content_for :main_content do %>
    <table>
      <tr>

        <th>Player</th>

        <th>Min allocation</th>

        <th>Max allocation</th>

        <th>Round</th>

        <th>Investment type</th>

        <th></th>
      </tr>

      <% @portfolio_allocations.each do |portfolio_allocation| %>
          <tr>

            <td><%= portfolio_allocation.player_id %></td>

            <td><%= portfolio_allocation.min_allocation %></td>

            <td><%= portfolio_allocation.max_allocation %></td>

            <td><%= portfolio_allocation.round_id %></td>

            <td><%= portfolio_allocation.investment_type_id %></td>

            <td>
              <%= link_to image_tag(icon("show"), :size=>"64x64"), portfolio_allocation, :title=>'Show' %>
              <%= link_to image_tag(icon("edit"), :size=>"64x64"), edit_portfolio_allocation_path(portfolio_allocation), :title=>'Edit' %>

            </td>
          </tr>
      <% end %>
    </table>
<% end %>

<br/>
<%= content_for :navigation do %>
<% end %>
<%= content_for :extra do %>

        <%= link_to image_tag('new_icon.png', :size=>"100x100"), new_portfolio_allocation_path(:player_id=>@player.id), :title=>"Add a portfolio_allocation" %>

<% end %>
<%= content_for :footer do %>
<% end %>


app/views/portfolio_allocations/new.html.erb
<%= content_for :header do %>
<h1>New portfolio_allocation</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), portfolio_allocations_path(:player_id=>@player.id), :title=>'Back' %>
<% end %>


app/views/portfolio_allocations/show.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :header do %>
<% end %>

<%= content_for :main_content do %>


    <p>
      <b>Player:</b>
      <%= @portfolio_allocation.player_id %>
    </p>


    <p>
      <b>Min allocation:</b>
      <%= @portfolio_allocation.min_allocation %>
    </p>


    <p>
      <b>Max allocation:</b>
      <%= @portfolio_allocation.max_allocation %>
    </p>


    <p>
      <b>Round:</b>
      <%= @portfolio_allocation.round_id %>
    </p>


    <p>
      <b>Investment type:</b>
      <%= @portfolio_allocation.investment_type_id %>
    </p>



<% end %>
<br/>
<br/>
<%= content_for :navigation do %>
<% end %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("edit"),:size=>"100x100"), edit_portfolio_allocation_path(@portfolio_allocation,:player_id=>@player.id), :title=>'Edit' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), portfolio_allocations_path(:player_id=>@player.id), :title=>'Back' %>
<% end %>

<%= content_for :footer do %>
<% end %>