config/routes.rb
Layouter::Application.routes.draw do

  resources :facilitators

  resources :imports

  resources :news_sectors

  resources :round_stock_constants

  resources :constants

  resources :player_clients

  resources :news_companies

  resources :client_earnings

  resources :player_earnings

  resources :client_transactions

  resources :player_transactions

  resources :client_players

  resources :clients

  resources :player_assessments

  resources :portfolio_allocations

  resources :player_promises

  resources :player_fee_structures

  resources :company_financials

  resources :investment_types

  resources :economic_parameter_values

  resources :economic_parameter_s

  resources :round_news

  resources :rounds

  resources :simulations

  resources :economic_parameters

  resources :news

  resources :scheme_prices

  resources :schemes

  resources :gold_prices

  resources :fixed_deposits

  resources :debt_paper_prices

  resources :debt_papers

  resources :stock_prices

  resources :stocks

  resources :companies

  resources :sectors

  resources :players

  resources :student_group_users

  resources :facilitator_groups

  resources :student_groups

  devise_for :users
  root :to=>'welcome#landing_page'
  resources :plugin_samples
  resources :jquery_themes
  resources :font_themes
  resources :icon_themes
  resources :temps
  resources :pages
  resources :page_layouts
  resources :layout_themes
  resources :color_themes


  #my get routes
  get '/landing_page'=>'welcome#landing_page'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match 'initiate_round'=>'simulations#initiate_round'
  match 'start_round'=>'simulations#start_round'
  match 'end_round'=>'simulations#end_round'
  match 'player_decision_page'=>'welcome#decision_page'
  match 'player_transaction_page'=>'welcome#transaction_page'
  match 'company_stock_prices'=>'stock_prices#get_stock_prices_in_json'
  match 'current_stock_price' =>'stock_prices#get_current_stock_price'






end

app/models/player_client.rb
class PlayerClient < ActiveRecord::Base
end

app/controllers/player_clients_controller.rb
class PlayerClientsController < ApplicationController
  # GET /player_clients
  # GET /player_clients.json
  def index
    @player_clients = PlayerClient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @player_clients }
    end
  end

  # GET /player_clients/1
  # GET /player_clients/1.json
  def show
    @player_client = PlayerClient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player_client }
    end
  end

  # GET /player_clients/new
  # GET /player_clients/new.json
  def new
    @player_client = PlayerClient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player_client }
    end
  end

  # GET /player_clients/1/edit
  def edit
    @player_client = PlayerClient.find(params[:id])
  end

  # POST /player_clients
  # POST /player_clients.json
  def create
    @player_client = PlayerClient.new(params[:player_client])

    respond_to do |format|
      if @player_client.save
        format.html { redirect_to @player_client, notice: 'Player client was successfully created.' }
        format.json { render json: @player_client, status: :created, location: @player_client }
      else
        format.html { render action: "new" }
        format.json { render json: @player_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /player_clients/1
  # PUT /player_clients/1.json
  def update
    @player_client = PlayerClient.find(params[:id])

    respond_to do |format|
      if @player_client.update_attributes(params[:player_client])
        format.html { redirect_to @player_client, notice: 'Player client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @player_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_clients/1
  # DELETE /player_clients/1.json
  def destroy
    @player_client = PlayerClient.find(params[:id])
    @player_client.destroy

    respond_to do |format|
      format.html { redirect_to player_clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/player_clients_helper.rb
module PlayerClientsHelper
end

app/views/player_clients/_form.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :main_content do %>

<%= form_for(@player_client) do |f| %>
<% if @player_client.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@player_client.errors.count, "error") %> prohibited this player_client
    from being saved:</h2>

  <ul>
    <% @player_client.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


    <%= f.label :player_id %><br/>
    <%= f.number_field :player_id %>
    <br/><br/>

    <%= f.label :client_id %><br/>
    <%= f.number_field :client_id %>
    <br/><br/>

<p><%= f.submit %></p>
<% end %>
<% end %>

<%= content_for :navigation do %>
<% end %>
<%= content_for :footer do %>
<% end %>

app/views/player_clients/edit.html.erb

<%= content_for :header do %>
<h1>Editing player_client</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("show"),:size=>"100x100"), @player_client, :title=>'Show' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), player_clients_path, :title=>'Back' %>
<% end %>

app/views/player_clients/index.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :header do %>
<h1>Listing player_clients</h1>
<% end %>

<%= content_for :main_content do %>
<table>
  <tr>

    <th>Player</th>

    <th>Client</th>

    <th></th>
  </tr>

<% @player_clients.each do |player_client| %>
  <tr>

    <td><%= player_client.player_id %></td>

    <td><%= player_client.client_id %></td>

    <td>
    <%= link_to image_tag(icon("show"),:size=>"64x64"), player_client, :title=>'Show' %>
    <%= link_to image_tag(icon("edit"),:size=>"64x64"), edit_player_client_path(player_client), :title=>'Edit' %>
    <%= link_to image_tag(icon("delete"),:size=>"64x64"), player_client, confirm: 'Are you sure?', method: :delete, :title=>'Delete' %>
    </td>
  </tr>
<% end %>
</table>
<% end %>

<br />
<%= content_for :navigation do %>
<% end %>
<%= content_for :extra do %>
<%= link_to image_tag('new_icon.png',:size=>"100x100"), new_player_client_path, :title=>"Add a player_client" %>
<% end %>
<%= content_for :footer do %>
<% end %>


app/views/player_clients/new.html.erb
<%= content_for :header do %>
<h1>New player_client</h1>
<% end %>


<%= render 'form' %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), player_clients_path, :title=>'Back' %>
<% end %>


app/views/player_clients/show.html.erb
<%= content_for :head do %>
<script type="text/javascript">
    $(function() {
    });
</script>
<% end %>

<%= content_for :header do %>
<% end %>

<%= content_for :main_content do %>


    <p>
      <b>Player:</b>
      <%= @player_client.player_id %>
    </p>


    <p>
      <b>Client:</b>
      <%= @player_client.client_id %>
    </p>



<% end %>
<br/>
<br/>
<%= content_for :navigation do %>
<% end %>

<%= content_for :extra do %>
<%= link_to image_tag(icon("edit"),:size=>"100x100"), edit_player_client_path(@player_client), :title=>'Edit' %>
<%= link_to image_tag(icon("back"),:size=>"100x100"), player_clients_path, :title=>'Back' %>
<% end %>

<%= content_for :footer do %>
<% end %>