config/routes.rb
Layouter::Application.routes.draw do

  resources :facilitators

  resources :imports

  resources :news_sectors

  resources :round_stock_constants

  resources :constants

  resources :player_clients

  resources :news_companies

  resources :client_earnings

  resources :player_earnings

  resources :client_transactions

  resources :player_transactions

  resources :client_players

  resources :clients

  resources :player_assessments

  resources :portfolio_allocations

  resources :player_promises

  resources :player_fee_structures

  resources :company_financials

  resources :investment_types

  resources :economic_parameter_values

  resources :economic_parameter_s

  resources :round_news

  resources :rounds

  resources :simulations

  resources :economic_parameters

  resources :news

  resources :scheme_prices

  resources :schemes

  resources :gold_prices

  resources :fixed_deposits

  resources :debt_paper_prices

  resources :debt_papers

  resources :stock_prices

  resources :stocks

  resources :companies

  resources :sectors

  resources :players

  resources :student_group_users

  resources :facilitator_groups

  resources :student_groups

  devise_for :users
  root :to=>'welcome#landing_page'
  resources :plugin_samples
  resources :jquery_themes
  resources :font_themes
  resources :icon_themes
  resources :temps
  resources :pages
  resources :page_layouts
  resources :layout_themes
  resources :color_themes


  #my get routes
  get '/landing_page'=>'welcome#landing_page'
  match 'initiate_simulation'=>'simulations#initiate_simulation'
  match 'initiate_round'=>'simulations#initiate_round'
  match 'start_round'=>'simulations#start_round'
  match 'end_round'=>'simulations#end_round'
  match 'player_decision_page'=>'welcome#decision_page'
  match 'player_transaction_page'=>'welcome#transaction_page'
  match 'company_stock_prices'=>'stock_prices#get_stock_prices_in_json'
  match 'current_stock_price' =>'stock_prices#get_current_stock_price'






end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/Partials/_basic.html.erb
<style>
    body {
        margin: 0 auto;
        background-color: #<%= back_color %>;
        color: #<%= text_color %>;
        <% if current_page_layout(params[:controller].parameterize,params[:action].parameterize) %>
        font-family: <%= current_page_layout(params[:controller].parameterize,params[:action].parameterize).font_theme.name %>;
        font-weight: <%= current_page_layout(params[:controller].parameterize,params[:action].parameterize).font_weight %>;
        font-size: <%= current_page_layout(params[:controller].parameterize,params[:action].parameterize).font_size %>px;
        <% end %>
    }

    div#header {
        background: transparent;
        background-color: #<%= header_color %>;
        color: #<%= header_text_color %>;
        text-indent: 20px;
    }

    div#header h1 {
        background: transparent;
        color: black;
        color: #<%= header_text_color %>;
    }

    div#navigation {
        background: transparent;
        background-color: #<%= navigation_panel_color %>;
    }

    div#extra {
        background: transparent;
        background-color: #<%= extra_panel_color %>;
    }

    div#footer {
        background: transparent;
        background-color: #<%= footer_panel_color %>;
    }

    #content {
        background: transparent;
        background-color: #<%= main_color %>;
        color: #<%= text_color %>;
    }

    a {
        color: #<%= link_color %>;
        text-decoration: none;
    }

    a:hover {
        color: #<%= link_color_hover %>;
    }

    #flash_notice {
        background-color: #<%= highlight_color %>;
    }

    #flash_error, #flash_alert {
        background-color: #<%= highlight_color %>;
    }

    <% if rounded_corners %>
    #header {
        border-radius: 10px;
    }

    #content {
        border-radius: 10px;
    }

    #navigation {
        border-radius: 10px;
    }

    #footer {
        border-radius: 10px;
    }

    #extra {
        border-radius: 10px;
    }
    
    <% end %>
        
</style>

app/views/layouts/Partials/_icon_sample.html.erb
<table>
  <tr>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/new.png", :size=>"64x64", :title=>"New") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/show.png", :size=>"64x64", :title=>"Show") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/edit.png", :size=>"64x64", :title=>"Edit") %></td>
  </tr>
  <tr>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/delete.png", :size=>"64x64", :title=>"Delete") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/back.png", :size=>"64x64", :title=>"Back") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/settings.png", :size=>"64x64", :title=>"Settings") %></td>
  </tr>
  <tr>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/layout.png", :size=>"64x64", :title=>"Layout") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/theme.png", :size=>"64x64", :title=>"Theme") %></td>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/home.png", :size=>"64x64", :title=>"Home") %></td>
  </tr>
  <tr>
    <td><%= image_tag("icon_packs/icon_pack_#{@icon_theme}/search.png", :size=>"64x64", :title=>"Search") %></td>
  </tr>
</table>



app/views/layouts/Partials/_navigation_horizontal.html.erb
<!-- This is the Admin Control which only the Admin should get to see -->

<%# if current_user.admin  %>

<% if @current_page_layout %>
    <%= link_to image_tag(icon("home"), :size=>"100x100"), '/', :title=> "Home" %>
    <%= link_to image_tag(icon("layout"), :size=>"100x100"), edit_page_layout_path(@current_page_layout, :page_id=>@current_page.id, :path=>request.fullpath), :title=> "Select layout for this controller-action combination" %>
    <%= link_to image_tag(icon("theme"), :size=>"100x100"), edit_color_theme_path(ColorTheme.first), :title=> "Select a color theme" %>
    <%= link_to image_tag(icon("search"), :size=>"100x100"), plugin_samples_path, :title=> "Built-in JQuery Plugins " %>
<% else %>
    <% if params[:controller] == "page_layouts" %>
    <% else %>
        <%= link_to image_tag(icon("home"), :size=>"100x100"), '/', :title=> "Home" %>
        <%= link_to image_tag(icon("layout"), :size=>"100x100"), new_page_layout_path(:controller_name=>params[:controller].parameterize, :action_name=>params[:action].parameterize, :path=>request.fullpath), :title=> "Select layout for this controller-action combination" %>
        <%= link_to image_tag(icon("theme"), :size=>"100x100"), edit_color_theme_path(ColorTheme.first), :title=> "Select a color theme" %>
        <%= link_to image_tag(icon("search"), :size=>"100x100"), plugin_samples_path, :title=> "Built-in JQuery Plugins " %>
    <% end %>
<% end %>

<%# end  %>

<!-- End of Admin Control Panel -->

<!-- This is the Regular Navigation Panel which everybody gets to see -->

<!-- End of Regular Navigation Panel -->

app/views/layouts/Partials/_navigation_vertical.html.erb
<!-- This is the Admin Control which only the Admin should get to see -->

<% if current_user %>
<% if current_user.admin  %>

<% if @current_page_layout %>
    <%= link_to image_tag(icon("home"), :size=>"80x80"), '/', :title=> "Home" %>
    <br/>
    <%= link_to image_tag(icon("layout"), :size=>"80x80"), edit_page_layout_path(@current_page_layout, :page_id=>@current_page.id, :path=>request.fullpath), :title=> "Select layout for this controller-action combination" %>
    <br/>
    <%= link_to image_tag(icon("theme"), :size=>"80x80"), edit_color_theme_path(ColorTheme.first), :title=> "Select a color theme" %>
    <br/>
    <%= link_to image_tag(icon("search"), :size=>"80x80"), plugin_samples_path, :title=> "Built-in JQuery Plugins " %>
    <br/>
<% else %>
    <% if params[:controller] == "page_layouts" %>
    <% else %>
        <%= link_to image_tag(icon("home"), :size=>"80x80"), '/', :title=> "Home" %>
        <br/>
        <%= link_to image_tag(icon("layout"), :size=>"80x80"), new_page_layout_path(:controller_name=>params[:controller].parameterize, :action_name=>params[:action].parameterize, :path=>request.fullpath), :title=> "Select layout for this controller-action combination" %>
        <br/>
        <%= link_to image_tag(icon("theme"), :size=>"80x80"), edit_color_theme_path(ColorTheme.first), :title=> "Select a color theme" %>
        <br/>
        <%= link_to image_tag(icon("search"), :size=>"80x80"), plugin_samples_path, :title=> "Built-in JQuery Plugins " %>
        <br/>
    <% end %>
<% end %>

<% end  %><% end  %>

<!-- End of Admin Control Panel -->

<!-- This is the Regular Navigation Panel which everybody gets to see -->

<!-- End of Regular Navigation Panel -->